### ISSUE TITLE
thor似乎会过期

### ISSUE THREAD

**Issue by dream-seeker-steven** [dengbaikun/jdh5st#1]
会提示
{"code":"605","echo":"the request needs to authenticate"}

**Comment by dream-seeker-steven** [comment]
我已使用了自己账号

**Comment by dengbaikun** [comment]
你要用会自己的cookie参数 这个主要是防止请求频繁出现滑动验证码

**Comment by dream-seeker-steven** [comment]
> 你要用会自己的cookie参数 这个主要是防止请求频繁出现滑动验证码

我已使用了自己的cookie，但依旧会出现605，这个如何尽量避免呢，您的项目中哪些参数是需要重点关注的，我发现似乎thor在官网中是会刷新的，我使用了刷新后的thor偶尔能避免605，但很快失效

**Comment by dengbaikun** [comment]
algo接口获取到 token algo fingerPrint 这个有时间限制 你看源码就知道了 过期要重新获取

**Comment by dengbaikun** [comment]
你试下用登录后的cookie吧  你是请求频繁了吧

**Comment by dream-seeker-steven** [comment]
> 你试下用登录后的cookie吧 你是请求频繁了吧

用了的，我再调试一下，感谢大佬

**Comment by dream-seeker-steven** [comment]
> 你试下用登录后的cookie吧 你是请求频繁了吧

出现滑动验证码后，似乎后序请求都是失败，这个有解吗😂

**Comment by dengbaikun** [comment]
> > 你试下用登录后的cookie吧你是请求关闭吧
> 
> 出现滑动验证码后，好像后序请求都失败了，这个有解吗😂

可以通过selenium 加载页面 控制滑块 模拟滑动块 像人滑动 把它破解掉 我这这样处理过 面对吖阿里云以及京东这种的
