### ISSUE TITLE
执行例程报错execjs._exceptions.ProgramError: SyntaxError: 缺少标识符

### ISSUE THREAD

**Issue by btwang98** [dengbaikun/jdh5st#2]
没有任何改动，执行python .\jd_h5st.py
报错位置为
File "D:\project\jupyter_home\jdmonitor\jdh5st\h5st.py", line 181, in get_algo
    fp = execjs.compile(js).call("fingerPrint")
我看了一下，这个js函数本身也没有参数传递，不知道是什么原因。
改成优化版.js也一样报错

**Comment by dengbaikun** [comment]
> 没有任何改动，执行python .\jd_h5st.py 报错位置为 File "D:\project\jupyter_home\jdmonitor\jdh5st\h5st.py", line 181, in get_algo fp = execjs.compile(js).call("fingerPrint") 我看了一下，这个js函数本身也没有参数传递，不知道是什么原因。 改成优化版.js也一样报错

代码应该不会有问题 nodejs 环境有安装吗 并且配置nodejs环境  我的版本是18

**Comment by dengbaikun** [comment]
> fp = execjs.compile(js).call("fingerPrint")

你这里错了 
![image](https://github.com/dengbaikun/jdh5st/assets/48817023/9b3ac512-69e6-475b-a3eb-bc235f10a2ab)
应该是 fp = execjs.compile(js).call("genFingerPrint")

**Comment by btwang98** [comment]
> > fp = execjs.compile(js).call("fingerPrint")
> 
> 你这里错了 ![image](https://private-user-images.githubusercontent.com/48817023/320271016-9b3ac512-69e6-475b-a3eb-bc235f10a2ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM0OTEsIm5iZiI6MTcxMjQ4MzE5MSwicGF0aCI6Ii80ODgxNzAyMy8zMjAyNzEwMTYtOWIzYWM1MTItNjllNi00NzViLWEzZWItYmMyMzVmMTBhMmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNjA4NDgzMzMxMmM4NzAxNjIzYTk4ODdiYTMyYjg3ODg2NzYwN2U1Mzk1NTY5YWI3YzY5OWVkYzgwYzQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7nQ4OP67nqvq6EtAskip0AJA9Hf197R390M8aJECB_4) 应该是 fp = execjs.compile(js).call("genFingerPrint")

抱歉粘错了，是原来的genFingerPrint。我没有安装nodejs，我再试一下。

**Comment by dengbaikun** [comment]
对的 你安装完nodejs 配置好环境就重新打开噶pycharm 如果用pycharm的话

**Comment by btwang98** [comment]
感谢指导！

安装了node.js环境以及crypto-js包，现在运行正常了。
```
conda install -c anaconda nodejs
npm install crypto-js --save
```

**Comment by dengbaikun** [comment]
OK 麻烦点噶赞支持一下 感谢
