### ISSUE TITLE
python 3.11 报错

### ISSUE THREAD

**Issue by qrpengx** [dengbaikun/jdh5st#3]
execjs._exceptions.ProgramError: SyntaxError: 缺少标识符

**Comment by dengbaikun** [comment]
> execjs._exceptions.ProgramError: SyntaxError: 缺少标识符

可以发多点信息么或者截图，让我更好的帮你看问题出在哪里，有装nodejs环境吗？

**Comment by qrpengx** [comment]
> > execjs._exceptions.ProgramError: SyntaxError: 缺少标识符
> 
> 可以发多点信息么或者截图，让我更好的帮你看问题出在哪里，有装nodejs环境吗？

没装nodejs环境 是因为这个原因吗

**Comment by dengbaikun** [comment]
> > > execjs._exceptions.ProgramError: SyntaxError: 缺少标识符
> > 
> > 
> > 可以发多点信息么或者截图，让我更好的帮你看问题出在哪里，有装nodejs环境吗？
> 
> 没装nodejs环境 是因为这个原因吗

如果你代码没变动过 就是nodejs nodejs要装一下 不装你可以把js的代用python补完 fp那段代码已经完全解析出来可以用python仿写一下

**Comment by qrpengx** [comment]
> > > > execjs._exceptions.ProgramError: SyntaxError: 缺少标识符
> > > 
> > > 
> > > 可以发多点信息么或者截图，让我更好的帮你看问题出在哪里，有装nodejs环境吗？
> > 
> > 
> > 没装nodejs环境 是因为这个原因吗
> 
> 如果你代码没变动过 就是nodejs nodejs要装一下 不装你可以把js的代用python补完 fp那段代码已经完全解析出来可以用python仿写一下

安装了 npm install crypto-js 就没报错了 感谢

**Comment by dengbaikun** [comment]
麻烦点个星星 点噶赞  感谢

**Comment by qrpengx** [comment]
> 麻烦点个星星 点噶赞 感谢

点了 😳

**Comment by dengbaikun** [comment]
> > 麻烦点个星星 点噶赞 感谢
> 
> 点了 😳

感谢 感觉你们是为了抢购？秒杀的 估计后面会发布抢购秒杀代码pc端

**Comment by qrpengx** [comment]
> > > 麻烦点个星星 点噶赞 感谢
> > 
> > 
> > 点了 😳
> 
> 感谢 感觉你们是为了抢购？秒杀的 估计后面会发布抢购秒杀代码pc端

并没有 目前只是为了京豆

**Comment by qrpengx** [comment]
把appId换成4646c 返回 <Response [403]>

**Comment by dengbaikun** [comment]
> 把appId换成4646c 返回 <Response [403]>

可以截图改了那些吗？你要对上你浏览器的接口参数

**Comment by qrpengx** [comment]
> 浏览器的接口参数
 h5st.py 中的 appid 
把 'fb5df' 全部改成 ‘4646c’

 jd_h5st.py 中 
在self.cookies 添加了 我的 pt_key pt_pin 更新了 __jdu  shshshfpa shshshfpx TrackID

def getPcItemSoa 修改如图
![image](https://github.com/dengbaikun/jdh5st/assets/16115473/43028832-86e6-4b23-bf18-d1c1d5156132)

**Comment by dengbaikun** [comment]
> > 浏览器的接口参数
> > h5st.py 中的 appid
> > 把 'fb5df' 全部改成 ‘4646c’
> 
> jd_h5st.py 中 在self.cookies 添加了 我的 pt_key pt_pin 更新了 __jdu shshshfpa shshshfpx TrackID
> 
> def getPcItemSoa 修改如图 ![image](https://private-user-images.githubusercontent.com/16115473/321467049-43028832-86e6-4b23-bf18-d1c1d5156132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDI4NTksIm5iZiI6MTcxMjgwMjU1OSwicGF0aCI6Ii8xNjExNTQ3My8zMjE0NjcwNDktNDMwMjg4MzItODZlNi00YjIzLWJmMTgtZDFjMWQ1MTU2MTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAyMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTQwMjFhMjVkZDA2YzM2ZDVmYTcxYTkxYTFkYTlmYjFmZjA0YjNhNGI0OGNhOTk0YTE4ZDA1YTM5N2JlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCPrrkbl8tVuLcezxFL5YnRwX7CASpubUkKNXIJlZvI)

你有捕捉过生成请求接口只需要这些参数吗？

**Comment by qrpengx** [comment]
> > > 浏览器的接口参数
> > > h5st.py 中的 appid
> > > 把 'fb5df' 全部改成 ‘4646c’
> > 
> > 
> > jd_h5st.py 中 在self.cookies 添加了 我的 pt_key pt_pin 更新了 __jdu shshshfpa shshshfpx TrackID
> > def getPcItemSoa 修改如图 ![image](https://private-user-images.githubusercontent.com/16115473/321467049-43028832-86e6-4b23-bf18-d1c1d5156132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDI4NTksIm5iZiI6MTcxMjgwMjU1OSwicGF0aCI6Ii8xNjExNTQ3My8zMjE0NjcwNDktNDMwMjg4MzItODZlNi00YjIzLWJmMTgtZDFjMWQ1MTU2MTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAyMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTQwMjFhMjVkZDA2YzM2ZDVmYTcxYTkxYTFkYTlmYjFmZjA0YjNhNGI0OGNhOTk0YTE4ZDA1YTM5N2JlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCPrrkbl8tVuLcezxFL5YnRwX7CASpubUkKNXIJlZvI)
> 
> 你有捕捉过生成请求接口只需要这些参数吗？

任务入口 https://jdbeantask-pro.pf.jd.com/
目前加了 functionId appid body h5st  eid x-api-eid-token 都是返回403

**Comment by dengbaikun** [comment]
> > > > 浏览器的接口参数
> > > > h5st.py 中的 appid
> > > > 把 'fb5df' 全部改成 ‘4646c’
> > > 
> > > 
> > > jd_h5st.py 中 在self.cookies 添加了 我的 pt_key pt_pin 更新了 __jdu shshshfpa shshshfpx TrackID
> > > def getPcItemSoa 修改如图 ![image](https://private-user-images.githubusercontent.com/16115473/321467049-43028832-86e6-4b23-bf18-d1c1d5156132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDI4NTksIm5iZiI6MTcxMjgwMjU1OSwicGF0aCI6Ii8xNjExNTQ3My8zMjE0NjcwNDktNDMwMjg4MzItODZlNi00YjIzLWJmMTgtZDFjMWQ1MTU2MTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAyMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTQwMjFhMjVkZDA2YzM2ZDVmYTcxYTkxYTFkYTlmYjFmZjA0YjNhNGI0OGNhOTk0YTE4ZDA1YTM5N2JlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCPrrkbl8tVuLcezxFL5YnRwX7CASpubUkKNXIJlZvI)
> > 
> > 
> > 你有捕捉过生成请求接口只需要这些参数吗？
> 
> 任务入口 https://jdbeantask-pro.pf.jd.com/ 目前加了 functionId appid body h5st eid x-api-eid-token 都是返回403

不能直接这样改 我那个是针对着预约页面 你看回你那个接口 debug一下看回你那页面传递参数 我下班或者有空的时候 我去调一下 这里只是逆向了h5st生成方式

**Comment by qrpengx** [comment]
> > > > > 浏览器的接口参数
> > > > > h5st.py 中的 appid
> > > > > 把 'fb5df' 全部改成 ‘4646c’
> > > > 
> > > > 
> > > > jd_h5st.py 中 在self.cookies 添加了 我的 pt_key pt_pin 更新了 __jdu shshshfpa shshshfpx TrackID
> > > > def getPcItemSoa 修改如图 ![image](https://private-user-images.githubusercontent.com/16115473/321467049-43028832-86e6-4b23-bf18-d1c1d5156132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDI4NTksIm5iZiI6MTcxMjgwMjU1OSwicGF0aCI6Ii8xNjExNTQ3My8zMjE0NjcwNDktNDMwMjg4MzItODZlNi00YjIzLWJmMTgtZDFjMWQ1MTU2MTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAyMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTQwMjFhMjVkZDA2YzM2ZDVmYTcxYTkxYTFkYTlmYjFmZjA0YjNhNGI0OGNhOTk0YTE4ZDA1YTM5N2JlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCPrrkbl8tVuLcezxFL5YnRwX7CASpubUkKNXIJlZvI)
> > > 
> > > 
> > > 你有捕捉过生成请求接口只需要这些参数吗？
> > 
> > 
> > 任务入口 https://jdbeantask-pro.pf.jd.com/ 目前加了 functionId appid body h5st eid x-api-eid-token 都是返回403
> 
> 不能直接这样改 我那个是针对着预约页面 你看回你那个接口 debug一下看回你那页面传递参数 我下班或者有空的时候 我去调一下 这里只是逆向了h5st生成方式

期待大佬😳

**Comment by dengbaikun** [comment]
> > > > > > 浏览器的接口参数
> > > > > > h5st.py 中的 appid
> > > > > > 把 'fb5df' 全部改成 ‘4646c’
> > > > > 
> > > > > 
> > > > > jd_h5st.py 中 在self.cookies 添加了 我的 pt_key pt_pin 更新了 __jdu shshshfpa shshshfpx TrackID
> > > > > def getPcItemSoa 修改如图 ![image](https://private-user-images.githubusercontent.com/16115473/321467049-43028832-86e6-4b23-bf18-d1c1d5156132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDI4NTksIm5iZiI6MTcxMjgwMjU1OSwicGF0aCI6Ii8xNjExNTQ3My8zMjE0NjcwNDktNDMwMjg4MzItODZlNi00YjIzLWJmMTgtZDFjMWQ1MTU2MTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAyMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTQwMjFhMjVkZDA2YzM2ZDVmYTcxYTkxYTFkYTlmYjFmZjA0YjNhNGI0OGNhOTk0YTE4ZDA1YTM5N2JlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCPrrkbl8tVuLcezxFL5YnRwX7CASpubUkKNXIJlZvI)
> > > > 
> > > > 
> > > > 你有捕捉过生成请求接口只需要这些参数吗？
> > > 
> > > 
> > > 任务入口 https://jdbeantask-pro.pf.jd.com/ 目前加了 functionId appid body h5st eid x-api-eid-token 都是返回403
> > 
> > 
> > 不能直接这样改 我那个是针对着预约页面 你看回你那个接口 debug一下看回你那页面传递参数 我下班或者有空的时候 我去调一下 这里只是逆向了h5st生成方式
> 
> 期待大佬😳

![jd金豆签到](https://github.com/dengbaikun/jdh5st/assets/48817023/cc1713d7-2521-42e6-ab6a-e129fb9f312d) 我大致说下实现 你利用京东扫码 然后登陆进行debug就好了  他的验证是 js_security_v3_0.1.7.js 实现
跟h5st一样基本一样 
  你先自己能不能逆向实现以下 估计我后面会把代码放出来 让你们学习一下

**Comment by dengbaikun** [comment]
你有问题可以提出来
