### ISSUE TITLE
Response [403]

### ISSUE THREAD

**Issue by aiaimimi0920** [dengbaikun/jdh5st#4]
1. 直接运行`python jd.py` 会显示403
需要怎么解决这个问题？代码没有做任何修改
2. algo函数 是一个固定函数还是会根据不同的业务需求有不同的变化？每个不同的业务需要不同的algo函数吗？每个相同的业务的algo会不会因为时间动态变化？
3. fingerPrint 如果是固定函数，是不是可以直接写成python版本的
4. 这个东西是不是必须有用户的cookie才能使用，如果没有的话是不是无法得到一个有效的反馈？我是希望做一个查询价格的小插件，我无法要求这个用户cookie一定能提供，是否有其他办法规避掉？

jd的官方api真是一点都不好用，连价格查询api都没有
提前感谢大佬解答

**Comment by dengbaikun** [comment]
> 1. 直接运行`python jd.py` 会显示403
>    需要怎么解决这个问题？代码没有做任何修改
> 2. algo函数 是一个固定函数还是会根据不同的业务需求有不同的变化？每个不同的业务需要不同的algo函数吗？每个相同的业务的algo会不会因为时间动态变化？
> 3. fingerPrint 如果是固定函数，是不是可以直接写成python版本的
> 4. 这个东西是不是必须有用户的cookie才能使用，如果没有的话是不是无法得到一个有效的反馈？我是希望做一个查询价格的小插件，我无法要求这个用户cookie一定能提供，是否有其他办法规避掉？
> 
> jd的官方api真是一点都不好用，连价格查询api都没有 提前感谢大佬解答

运行这个jd_h5st.py

**Comment by dengbaikun** [comment]
> 1. 直接运行`python jd.py` 会显示403
>    需要怎么解决这个问题？代码没有做任何修改
> 2. algo函数 是一个固定函数还是会根据不同的业务需求有不同的变化？每个不同的业务需要不同的algo函数吗？每个相同的业务的algo会不会因为时间动态变化？
> 3. fingerPrint 如果是固定函数，是不是可以直接写成python版本的
> 4. 这个东西是不是必须有用户的cookie才能使用，如果没有的话是不是无法得到一个有效的反馈？我是希望做一个查询价格的小插件，我无法要求这个用户cookie一定能提供，是否有其他办法规避掉？
> 
> jd的官方api真是一点都不好用，连价格查询api都没有 提前感谢大佬解答

algo函数是有时间限制 不是固定 会变动的 fp是固定函数可以写python版本 可以参照fp优惠版写 完全解析了 价格哪块我没去看 是一样的 我这个也是拿商品信息进行抢购。用户cookie可以用扫码方式然后把cookie序列号到本地 可以检查用户是否过期 过期重新扫码登录就好了 可以通过邮箱方式 最近我也是在帮一个小伙去逆向金豆签到 他那个不是新版本是3.17 基本京东h5st方式一样 就是有些细微变化

**Comment by aiaimimi0920** [comment]
> 
> 运行这个jd_h5st.py

可以运行了，我改了cookie以后就可以了。但是用户没cookie怎么办？

**Comment by aiaimimi0920** [comment]
> > 1. 直接运行`python jd.py` 会显示403
> >    需要怎么解决这个问题？代码没有做任何修改
> > 2. algo函数 是一个固定函数还是会根据不同的业务需求有不同的变化？每个不同的业务需要不同的algo函数吗？每个相同的业务的algo会不会因为时间动态变化？
> > 3. fingerPrint 如果是固定函数，是不是可以直接写成python版本的
> > 4. 这个东西是不是必须有用户的cookie才能使用，如果没有的话是不是无法得到一个有效的反馈？我是希望做一个查询价格的小插件，我无法要求这个用户cookie一定能提供，是否有其他办法规避掉？
> > 
> > jd的官方api真是一点都不好用，连价格查询api都没有 提前感谢大佬解答
> 
> algo函数是有时间限制 不是固定 会变动的 fp是固定函数可以写python版本 可以参照fp优惠版写 完全解析了 价格哪块我没去看 是一样的 我这个也是拿商品信息进行抢购。用户cookie可以用扫码方式然后把cookie序列号到本地 可以检查用户是否过期 过期重新扫码登录就好了 可以通过邮箱方式 最近我也是在帮一个小伙去逆向金豆签到 他那个不是新版本是3.17 基本京东h5st方式一样 就是有些细微变化

大概明白了。因为这个algo函数是变动的，所以动态获取，又因为是js代码，所以即使是用python运行也必须在nodejs环境下。感觉移植到我的godot项目上难度又大了一分，还要支持js环境。。

cookie的话，我还是不死心，有没有不用获取cookie就能获得商品价格的办法？用京东的api里面带的access token 可以吗？

再次感谢解答，基本解答了所有疑惑

**Comment by dengbaikun** [comment]
> > > 1. 直接运行`python jd.py` 会显示403
> > >    需要怎么解决这个问题？代码没有做任何修改
> > > 2. algo函数 是一个固定函数还是会根据不同的业务需求有不同的变化？每个不同的业务需要不同的algo函数吗？每个相同的业务的algo会不会因为时间动态变化？
> > > 3. fingerPrint 如果是固定函数，是不是可以直接写成python版本的
> > > 4. 这个东西是不是必须有用户的cookie才能使用，如果没有的话是不是无法得到一个有效的反馈？我是希望做一个查询价格的小插件，我无法要求这个用户cookie一定能提供，是否有其他办法规避掉？
> > > 
> > > jd的官方api真是一点都不好用，连价格查询api都没有 提前感谢大佬解答
> > 
> > 
> > algo函数是有时间限制 不是固定 会变动的 fp是固定函数可以写python版本 可以参照fp优惠版写 完全解析了 价格哪块我没去看 是一样的 我这个也是拿商品信息进行抢购。用户cookie可以用扫码方式然后把cookie序列号到本地 可以检查用户是否过期 过期重新扫码登录就好了 可以通过邮箱方式 最近我也是在帮一个小伙去逆向金豆签到 他那个不是新版本是3.17 基本京东h5st方式一样 就是有些细微变化
> 
> 大概明白了。因为这个algo函数是变动的，所以动态获取，又因为是js代码，所以即使是用python运行也必须在nodejs环境下。感觉移植到我的godot项目上难度又大了一分，还要支持js环境。。
> 
> cookie的话，我还是不死心，有没有不用获取cookie就能获得商品价格的办法？用京东的api里面带的access token 可以吗？
> 
> 再次感谢解答，基本解答了所有疑惑

京东api不太清楚 或者你发些资料我看下

**Comment by aiaimimi0920** [comment]
https://jos.jd.com/apilistnew
就是京东官方的api，感觉不行，功能极其匮乏。

我还是外挂一个 playwright 浏览器吧，用户的cookie就能直接获得，不用手动输入了。直接从渲染好的页面获得我需要的信息吧。

**Comment by dengbaikun** [comment]
> https://jos.jd.com/apilistnew 就是京东官方的api，感觉不行，功能极其匮乏。
> 
> 我还是外挂一个 playwright 浏览器吧，用户的cookie就能直接获得，不用手动输入了。直接从渲染好的页面获得我需要的信息吧。

也可以
