### ISSUE TITLE
狗东反爬403如何破

### ISSUE THREAD

**Issue by luowl123** [dengbaikun/jdh5st#5]
在某个自动下单的脚本原来基础上面，结合网页最新的接口和你这个h5st库，刚开始测试成功下单，后面一直403，换了好多个请求库都不行，就差ip代理池了，用Java，postman偶尔可以成功拿到数据，浏览器一直都正常访问。
我直接用浏览器的copy as curl(bash)生成代码却一直都能拿数据。

**Comment by dengbaikun** [comment]
你用扫码方式保存cookie 然后session.request保持session请求 操作全部 然后使用有噶是环境检测出来 如果不是频繁请求的化 可以挂chales 或者 mitmproxy 代理请求试下  除非你ip被限流黑名单封禁 就用ip代理池去跑

**Comment by dengbaikun** [comment]
> 在某个自动下单的脚本原来基础上面，结合网页最新的接口和你这个h5st库，刚开始测试成功下单，后面一直403，换了好多个请求库都不行，就差ip代理池了，用Java，postman偶尔可以成功拿到数据，浏览器一直都正常访问。 我直接用浏览器的copy as curl(bash)生成代码却一直都能拿数据。

你用扫码方式保存cookie 然后session.request保持session请求 操作全部 然后使用有噶是环境检测出来 如果不是频繁请求的化 可以挂charles或者 mitmproxy 代理请求试下 除非你ip被限流黑名单封禁 就用ip代理池去跑

**Comment by luowl123** [comment]
> > 在某个自动下单的脚本原来基础上面，结合网页最新的接口和你这个h5st库，刚开始测试成功下单，后面一直403，换了好多个请求库都不行，就差ip代理池了，用Java，postman偶尔可以成功拿到数据，浏览器一直都正常访问。 我直接用浏览器的copy as curl(bash)生成代码却一直都能拿数据。
> 
> 你用扫码方式保存cookie 然后session.request保持session请求 操作全部 然后使用有噶是环境检测出来 如果不是频繁请求的化 可以挂charles或者 mitmproxy 代理请求试下 除非你ip被限流黑名单封禁 就用ip代理池去跑

还真是cookie的问题，那个项目[zas023](https://github.com/zas023)/[JdBuyer](https://github.com/zas023/JdBuyer)是有扫码登录的，但好像拿到cookie比浏览器上打开的网页少了很多信息；
我也尝试过用[rookie](https://github.com/thewh1teagle/rookie)直接从浏览器上读取cookie，直接带上这些cookie也是403，搞不懂，太笨拙[捂脸]
刚才我把所有请求头和cookie都换成对应接口在浏览器拿下来的信息又下单成功了[捂脸]

**Comment by dengbaikun** [comment]
> ookie比浏览器上打开的网页少了很多信息；
> 我也尝试过用[rookie](https://github.com/thewh1teagle/rookie)直接从浏览器上读取cookie，直接带上这些cookie也是403，搞不懂，太笨拙[捂脸]
> 刚才我把所有请求头和cookie都换成对应接口在浏览器拿下来的信息又下单成功了[捂脸]

因为大部分浏览器请求的cooke 没有用   用的好像就是thor pin token那些
